# Site settings
title: HSA San Francisco
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/hsa-docs" # the subpath of your site, e.g. /blog/
# url: "http://www.sfhsa.org/" # the base hostname & protocol for your site
# twitter_username: designincode
github_username:  slowbot

# Build settings
markdown: kramdown
