# Site settings
title: HSA San Francisco
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The San Francisco Human Services Agency (HSA) is a lifeline for 23% of San Franciscans, serving over 200,000 unique persons seeking food assistance, health care, elder care, job training, daycare, and other essential social services. Sfhsa.org serves as the proverbial *front door* to the agency with more than 30,000 unique visits to the website each month. The public facing website has the potential to provide information and services in a clear, helpful, effective way with the utmost dignity and respect for client experience. 
baseurl: "/hsa-docs" # the subpath of your site, e.g. /blog/
# url: "http://www.sfhsa.org/" # the base hostname & protocol for your site
# twitter_username: designincode
github_username:  slowbot

# Build settings
markdown: kramdown
